my_string = input('Опишите какая сейчас погода за окном в двух словах: ')
print(my_string)
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ',''))
print(my_string[0])
print(my_string[-1])